### PR TITLE
Ruby sample

### PR DESCRIPTION
**Pull request by bs90**
Didn't find Ruby sample so I created one.
Hope it will be helpful for other Ruby developers.

### CODE REVIEW

**Comment by iwaffles** [comment]
👋 Hi @bs90, thanks so much for the contribution 🎉 — it means a lot to us!

We'll take a look at it shortly :)

**Review by iwaffles — APPROVED** [review]
Tested it out and works as expected, great job!

Any thoughts on parameterizing the path to private key as you've got with all of the other vars on lines 4-18?

**Comment by bs90** [comment]
@iwaffles I just updated my code. Please have a look 🙃

**Review by iwaffles — APPROVED** [review]
Looks good to me! :shipit:

**Comment by iwaffles** [comment]
Thanks for the contribution @bs90 🎉

**Comment by bs90** [comment]
@iwaffles Thank you. Hope to see the link on Integration tutorials & samples pages soon. Great service!

**Pull request merged**
